export * from "./home.jsx"
export * from "./sign-up.jsx"
export * from "./kiyimlar.jsx"
export * from "./kitoblar.jsx"
export * from "./elektronika.jsx"
export * from "./mexanika.jsx"
export * from "./sport.jsx"
export * from "./o'quv.jsx"
export * from './card.jsx'